# Uncomment the next line to define a global platform for your project
 source 'https://cdn.cocoapods.org'
 source 'https://github.com/CocoaPods/Specs.git'

 platform :ios, '15.3'


target 'iosApp' do
   # Comment the next line if you don't want to use dynamic frameworks
   use_frameworks!
     pod 'composeApp', :path => '../composeApp'
     pod 'GoogleMLKit/BarcodeScanning'

   # Pods for iosApp

 end
